name: 'Lit-Review'

on:
  push:
    branches: [main]
  schedule:
    - cron: "* * 1 * * "

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '14.x'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run scipt and setup env var
        run: |
          DATA=$(node index.js)
          echo $DATA
          echo "DATA=$DATA" >> $GITHUB_ENV
      
      - name: Use env var
        run: echo ${{ env.DATA }}