name: 'Lit-Review'

on:
  push:
    branches: [main]
  schedule:
    - cron: "* * 1 * * "

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '14.x'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run script
        run: node index.js
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: EshaanAgg
          author_email: eshaan.aggarwal.cse21@itbhu.ac.in
          message: 'Update data'
          add: '*.txt'